packages:
  - apps/*
  - packages/*

overrides:
  deepmerge-ts: 8.0.0
  mysql2: 3.23.1

allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
